### ISSUE TITLE
Does the SSH work?

### ISSUE THREAD

**Issue by kszucs** [conda-forge/libgit2-feedstock#13]
@shadowwalkersb does it works?

In circleCI I see the following:
```bash
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - not found
```

Also programatically libgit2 doesn't have the feature:
git_libgit2_features() & GIT_FEATURE_SSH -> 0

Also `conda install libgit2` doesn't install libssh2

```bash
The following NEW packages will be INSTALLED:

    curl:    7.52.1-0 conda-forge
    libgit2: 0.25.0-0 conda-forge

Proceed ([y]/n)?
```

**Comment by shadowwalkersb** [comment]
Sorry, I have no idea about `libssh2_userauth_publickey_frommemory`. No clue why `libssh2` is not pulled in.

 @jakirkham , anyone we can ask for help?

**Comment by kszucs** [comment]
https://github.com/libgit2/libgit2/issues/4120 and https://github.com/libgit2/libgit2/pull/4036 might be related

also ccing @carlosmn and @ethomson

**Comment by kszucs** [comment]
@shadowwalkersb @ethomson How should I investigate this issue?

**Comment by kszucs** [comment]
After `conda install libssh2`:

```bash
/opt/conda/lib # nm -g libssh2.so | grep libssh2_userauth_publickey_frommemory
000000000002d33f T libssh2_userauth_publickey_frommemory
/opt/conda/lib #
```

So the symbol is there, but cmake cant detect it.

**Comment by kszucs** [comment]
The same `build.sh` in a reproduced environment based on `continuumio/miniconda3` docker image seems to work just fine:

$PREFIX is /opt/conda

```bash
root@2b0b0a94c0f6:/libgit2-0.25.1/build# cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX \
>          -DCMAKE_PREFIX_PATH=$PREFIX \
>          -DCMAKE_FIND_ROOT_PATH=$PREFIX \
>          -DCMAKE_BUILD_TYPE=Release \
> -DCMAKE_C_FLAGS=-L$PREFIX/lib
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /opt/conda/bin/pkg-config (found version "0.29.1")
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM
-- Performing Test HAVE_STRUCT_STAT_ST_MTIM - Success
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC
-- Performing Test HAVE_STRUCT_STAT_ST_MTIMESPEC - Failed
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC
-- Performing Test HAVE_STRUCT_STAT_MTIME_NSEC - Failed
-- Performing Test HAVE_STRUCT_STAT_NSEC
-- Performing Test HAVE_STRUCT_STAT_NSEC - Success
-- Checking for module 'libcurl'
--   Found libcurl, version 7.52.1
-- Found OpenSSL: /opt/conda/lib/libssl.so (found version "1.0.2k")
-- Could NOT find HTTP_Parser (missing:  HTTP_PARSER_INCLUDE_DIR HTTP_PARSER_LIBRARY)
-- http-parser was not found or is too old; using bundled 3rd-party sources.
-- Found ZLIB: /opt/conda/lib/libz.so (found version "1.2.8")
-- Checking for module 'libssh2'
--   Found libssh2, version 1.8.0
-- Looking for libssh2_userauth_publickey_frommemory in ssh2
-- Looking for libssh2_userauth_publickey_frommemory in ssh2 - found
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED
-- Performing Test IS_FVISIBILITY=HIDDEN_SUPPORTED - Success
-- Performing Test IS_WDOCUMENTATION_SUPPORTED
-- Performing Test IS_WDOCUMENTATION_SUPPORTED - Failed
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED
-- Performing Test IS_WNO-MISSING-FIELD-INITIALIZERS_SUPPORTED - Success
```

The only difference that I've used gcc 4.9.2 whereas the feedstock  4.8.2

**Comment by kszucs** [comment]
I've created a working docker image based on debian, using conda dependencies https://github.com/kszucs/dockers/blob/master/libgit2.debian

I don't see why can't cmake find `libssh2_userauth_publickey_frommemory` in the conda build.

**Comment by kszucs** [comment]
I've created a working docker image based on debian, using conda dependencies https://github.com/kszucs/dockers/blob/master/libgit2.debian

I don't understand why can't cmake find `libssh2_userauth_publickey_frommemory` in the conda build.

**Comment by jakirkham** [comment]
In the most recent [Linux build on `master`]( https://circleci.com/gh/conda-forge/libgit2-feedstock/61 ), am seeing the following. Same story with [macOS]( https://travis-ci.org/conda-forge/libgit2-feedstock/builds/493413043#L607-L609 ).

```
-- Checking for module 'libssh2'
--   Found libssh2, version 1.8.0
--   Resolved libraries: $PREFIX/lib/libssh2.so
-- Looking for libssh2_userauth_publickey_frommemory in $PREFIX/lib/libssh2.so
-- Looking for libssh2_userauth_publickey_frommemory in $PREFIX/lib/libssh2.so - found
```

However for [Windows]( https://ci.appveyor.com/project/conda-forge/libgit2-feedstock/builds/22379896/job/9mhh71jray85aoyu?fullLog=true#L644 ) am seeing the following.

```
-- LIBSSH2 not found. Set CMAKE_PREFIX_PATH if it is installed outside of the default search path.
```

IOW looks like this got fixed at some point. Windows has some sort of issue though.

**Comment by BastianZim** [comment]
I bumped into this issue on an ARM Mac. Any idea how to fix this?

Ref: `bool(pygit2.features & pygit2.GIT_FEATURE_SSH)` comes out as false.
I have 1.6.4 so newest version.
